# Generated by Django 5.2.15 on 2026-07-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
